# this app is given to argocd directly (copypaste into UI)
# and the rest is automatic
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/diversario/argocd-sync-waves'
    path: stages/
    targetRevision: main
    directory:
      include: '*.yaml'
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
