apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-3
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type": "cluster"
  template:
    metadata:
      name: "nginx-3-{{ .name }}"
      namespace: nginx-3
    spec:
      project: default
      sources:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 18.1.11
        helm:
          releaseName: nginx-3
          ignoreMissingValueFiles: true
          values: |
            startupProbe:
              enabled: true
              initialDelaySeconds: 15

            service:
              type: ClusterIP

            serverBlock: |-
              server {
                listen 0.0.0.0:8080;
                location / {
                  add_header "Content-Type" "text/plain";
                  return 200 "nginx 3";
                }
              }
      destination:
        server: "{{ .server }}"
        namespace: nginx-3
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        automated:
          selfHeal: true
      revisionHistoryLimit: 3
