apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-5
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
        matchLabels:
          test: ok
  template:
    metadata:
      name: "nginx-5-{{ .name }}"
      namespace: nginx-5
    spec:
      project: default
      sources:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 18.1.11
        helm:
          releaseName: nginx-5
          ignoreMissingValueFiles: true
          values: |
            startupProbe:
              enabled: true
              initialDelaySeconds: 15

            service:
              type: ClusterIP

            serverBlock: |-
              server {
                listen 0.0.0.0:8080;
                location / {
                  add_header "Content-Type" "text/plain";
                  return 200 "nginx 5";
                }
              }
      destination:
        server: "{{ .server }}"
        namespace: nginx-5
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        automated:
          selfHeal: true
      revisionHistoryLimit: 3
