apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    directory:
      include: '*.yaml'
    path: apps/stage-1
    repoURL: https://github.com/diversario/argocd-sync-waves
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
